# Generated by Django 4.0.3 on 2022-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='clikc_power',
        ),
        migrations.AddField(
            model_name='core',
            name='click_power',
            field=models.IntegerField(default=1),
        ),
    ]
